/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceship.battle;

import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Timer;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.TimerTask;
import static spaceship.battle.SpaceshipBattle.thr2;
import static spaceship.battle.SpaceshipBattle.thr3;
import static spaceship.battle.SpaceshipBattle.tiro1;
import static spaceship.battle.SpaceshipBattle.tiro2;

/**
 *
 * @author Arthur
 */
public class TelaClasse extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form Tela
     */
    public TelaClasse() {
        setLayout(new FlowLayout());
        initComponents();
        setLocationRelativeTo(null);
        p1button.setIcon(new ImageIcon(getClass().getResource("ICN/spr2.png")));
        p2button.setIcon(new ImageIcon(getClass().getResource("ICN/vil2.png")));
        fundo.setIcon(new ImageIcon(getClass().getResource("ICN/BKG2.png")));
        xa1=120;ya1=200;p1button.setLocation(xa1, ya1);
        xa2=120;ya2=0;p2button.setLocation(xa2, ya2);
        tiro2 = new Tiro2();
        tiro1 = new Tiro1();
        ts=ya1;td=ya2;
//        shoot1.setIcon(new ImageIcon(getClass().getResource("ICN/Transparent.png"))); 
//        shoot2.setIcon(new ImageIcon(getClass().getResource("ICN/Transparent.png"))); 
        
        p1button.setLocation(xa1, ya1);
        p2button.setLocation(xa2, ya2);
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ICN/icon.png")));
    }
        int xa1=120,ya1=200;
        int xa2=120,ya2=0;
        char enabletiro1='B',enabletiro2='B';
        char pause='N';
        Timer timer;
        int tempotiro1 = 200;
        int SOME=0;
        boolean gameover = false;
        
        boolean esperatiro1=true, esperatiro2=true, para=false;
        
        int ts=ya1,td=ya2;
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        winlose1 = new javax.swing.JLabel();
        winlose2 = new javax.swing.JLabel();
        U1l = new javax.swing.JLabel();
        D1l = new javax.swing.JLabel();
        C1l = new javax.swing.JLabel();
        U2l = new javax.swing.JLabel();
        D2l = new javax.swing.JLabel();
        C2l = new javax.swing.JLabel();
        logoIcon = new javax.swing.JLabel();
        gameOver = new javax.swing.JLabel();
        vida2 = new javax.swing.JLabel();
        vida1 = new javax.swing.JLabel();
        p1button = new javax.swing.JLabel();
        shoot1 = new javax.swing.JLabel();
        p2button = new javax.swing.JLabel();
        shoot2 = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SpaceShip Battle");
        setMinimumSize(new java.awt.Dimension(320, 320));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        winlose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceship/battle/ICN/Transparent.png"))); // NOI18N
        winlose1.setToolTipText("");
        getContentPane().add(winlose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        winlose2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceship/battle/ICN/Transparent.png"))); // NOI18N
        winlose2.setToolTipText("");
        getContentPane().add(winlose2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));
        getContentPane().add(U1l, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 20, 30));
        getContentPane().add(D1l, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 270, 20, 30));
        getContentPane().add(C1l, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 20, 30));
        getContentPane().add(U2l, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 20, 30));
        getContentPane().add(D2l, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 20, 30));
        getContentPane().add(C2l, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 20, 30));

        logoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceship/battle/ICN/icon.png"))); // NOI18N
        getContentPane().add(logoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 256, -1, -1));

        gameOver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceship/battle/ICN/gameover.png"))); // NOI18N
        gameOver.setToolTipText("");
        getContentPane().add(gameOver, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, 0, -1, -1));

        vida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceship/battle/CONT/ROSA/cont3.png"))); // NOI18N
        getContentPane().add(vida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 255, -1, -1));

        vida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceship/battle/CONT/AZUL/cont3.png"))); // NOI18N
        getContentPane().add(vida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 255, -1, -1));

        p1button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceship/battle/ICN/spr2.png"))); // NOI18N
        p1button.setText("jLabel1");
        getContentPane().add(p1button, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 60, 60));

        shoot1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceship/battle/ICN/shoot1.png"))); // NOI18N
        shoot1.setText("jLabel1");
        getContentPane().add(shoot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-500, 0, 60, 50));

        p2button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceship/battle/ICN/vil2.png"))); // NOI18N
        p2button.setText("jLabel1");
        getContentPane().add(p2button, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 60, 60));

        shoot2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceship/battle/ICN/shoot2.png"))); // NOI18N
        shoot2.setText("jLabel1");
        getContentPane().add(shoot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-500, 0, 60, 50));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceship/battle/ICN/BKG2.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if(SpaceshipBattle.telaclasse.para==false){
        if(evt.getKeyCode() == KeyEvent.VK_A){
            SpaceshipBattle.move.left1=true;
        }
        if(evt.getKeyCode() == KeyEvent.VK_D){
            SpaceshipBattle.move.right1=true;
        }
        if(evt.getKeyCode() == KeyEvent.VK_W){
            SpaceshipBattle.move.up1=true;
        }
        if(evt.getKeyCode() == KeyEvent.VK_S){
            SpaceshipBattle.move.down1=true;
        }
        
        if(esperatiro1 && evt.getKeyCode() == KeyEvent.VK_G || esperatiro1 && evt.getKeyCode() == KeyEvent.VK_SPACE){
            enabletiro1='A';
            esperatiro1=false;
        }
        
        
}

        if(evt.getKeyCode() == KeyEvent.VK_ENTER && gameover){
            p1button.setIcon(new ImageIcon(getClass().getResource("ICN/spr2.png")));
        p2button.setIcon(new ImageIcon(getClass().getResource("ICN/vil2.png")));
        fundo.setIcon(new ImageIcon(getClass().getResource("ICN/BKG2.png")));
        xa1=120;ya1=200;p1button.setLocation(xa1, ya1);
        xa2=120;ya2=0;p2button.setLocation(xa2, ya2);
            
            SpaceshipBattle.contavida.vidap2=3;
            SpaceshipBattle.contavida.vidap1=3;
            
            SpaceshipBattle.pontuacao.C1=0;     
            SpaceshipBattle.pontuacao.D1=0;
            SpaceshipBattle.pontuacao.U1=0;
            SpaceshipBattle.pontuacao.C2=0;
            SpaceshipBattle.pontuacao.D2=0;
            SpaceshipBattle.pontuacao.U2=0;
            
                    SpaceshipBattle.telaclasse.C1l.setLocation(SpaceshipBattle.telaclasse.C1l.getLocation().x,270);
                    SpaceshipBattle.telaclasse.D1l.setLocation(SpaceshipBattle.telaclasse.D1l.getLocation().x,270);
                    SpaceshipBattle.telaclasse.U1l.setLocation(SpaceshipBattle.telaclasse.U1l.getLocation().x,270);
                    
                    SpaceshipBattle.telaclasse.C2l.setLocation(SpaceshipBattle.telaclasse.C2l.getLocation().x,270);
                    SpaceshipBattle.telaclasse.D2l.setLocation(SpaceshipBattle.telaclasse.D2l.getLocation().x,270);
                    SpaceshipBattle.telaclasse.U2l.setLocation(SpaceshipBattle.telaclasse.U2l.getLocation().x,270);
                    
                    SpaceshipBattle.telaclasse.winlose1.setIcon(new ImageIcon(getClass().getResource("ICN/Transparent.png")));
                    SpaceshipBattle.telaclasse.winlose2.setIcon(new ImageIcon(getClass().getResource("ICN/Transparent.png")));
                    
                    SpaceshipBattle.telaclasse.logoIcon.setIcon(new ImageIcon(getClass().getResource("ICN/icon.png")));
            
                    Contavida.PegaPontos();
                    
            gameOver.setLocation(-320, 0);
            gameover=false;
            para=false;
        }
        
        //jogador2 (de cima)
        if(SpaceshipBattle.telaclasse.para==false){
        if(evt.getKeyCode() == KeyEvent.VK_LEFT){
            SpaceshipBattle.move2.left2=true;
        }
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT){
            SpaceshipBattle.move2.right2=true;
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            SpaceshipBattle.move2.up2=true;
        }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            SpaceshipBattle.move2.down2=true;
        }
        if(esperatiro2 && evt.getKeyCode() == KeyEvent.VK_NUMPAD0 || esperatiro2 && evt.getKeyCode() == KeyEvent.VK_M){
            enabletiro2='A';
            esperatiro2=false;
            }
        }
        
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        if(SpaceshipBattle.telaclasse.para==false){
        if(evt.getKeyCode() == KeyEvent.VK_A){
            SpaceshipBattle.move.left1=false;
        }
        else if(evt.getKeyCode() == KeyEvent.VK_D){
            SpaceshipBattle.move.right1=false;
        }
        if(evt.getKeyCode() == KeyEvent.VK_W){
            SpaceshipBattle.move.up1=false;
        }
        else if(evt.getKeyCode() == KeyEvent.VK_S){
            SpaceshipBattle.move.down1=false;
        }
        }        
        
        if(evt.getKeyCode() == KeyEvent.VK_G || evt.getKeyCode() == KeyEvent.VK_SPACE ){
            esperatiro1=true;
        }
        if(evt.getKeyCode() == KeyEvent.VK_NUMPAD0 || evt.getKeyCode() == KeyEvent.VK_M ){
            esperatiro2=true;
        }
        
        //jogador2
        if(SpaceshipBattle.telaclasse.para==false){
        if(evt.getKeyCode() == KeyEvent.VK_LEFT){
            SpaceshipBattle.move2.left2=false;
        }
        else if(evt.getKeyCode() == KeyEvent.VK_RIGHT){
            SpaceshipBattle.move2.right2=false;
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            SpaceshipBattle.move2.up2=false;
        }
        else if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            SpaceshipBattle.move2.down2=false;
        }
        }
        
    }//GEN-LAST:event_formKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        SpaceshipBattle.tocarsom.clip.stop();
        SpaceshipBattle.thr1.stop();
        SpaceshipBattle.thr2.stop();
        SpaceshipBattle.thr3.stop();
        SpaceshipBattle.thr4.stop();
        SpaceshipBattle.thr5.stop();
        SpaceshipBattle.thr6.stop();
        SpaceshipBattle.thr7.stop();
        SpaceshipBattle.thr8.stop();
        SpaceshipBattle.thr9.stop();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClasse().setVisible(true);
            }
        });
    }

    public void checaLugar (){
    if (xa1 < -24){
    xa1 = -24;}
    if (xa1 > 276){
    xa1 = 276;
    }
    if (ya1 < 110){
    ya1 = 110;}
    if (ya1 > 210){
    ya1 = 210;
    }
    
    
    if (xa2 < -24){
    xa2 = -24;}
    if (xa2 > 276){
    xa2 = 276;
    }
    if (ya2 < -6){
    ya2 = -6;}
    if (ya2 > 90){
    ya2 = 90;
    }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel C1l;
    public javax.swing.JLabel C2l;
    public javax.swing.JLabel D1l;
    public javax.swing.JLabel D2l;
    public javax.swing.JLabel U1l;
    public javax.swing.JLabel U2l;
    private javax.swing.JLabel fundo;
    public static javax.swing.JLabel gameOver;
    public static javax.swing.JLabel logoIcon;
    public javax.swing.JLabel p1button;
    public javax.swing.JLabel p2button;
    public javax.swing.JLabel shoot1;
    public javax.swing.JLabel shoot2;
    public javax.swing.JLabel vida1;
    public static javax.swing.JLabel vida2;
    public static javax.swing.JLabel winlose1;
    public static javax.swing.JLabel winlose2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
