/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno Tarde
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Login_Cadastro
     */
    public Cadastro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        SenhaCadastro2 = new javax.swing.JPasswordField();
        SenhaCadastro1 = new javax.swing.JPasswordField();
        EmailCadastro = new javax.swing.JTextField();
        NomeCadastro = new javax.swing.JTextField();
        RSeguranca = new javax.swing.JTextField();
        PSegurancaCombo = new javax.swing.JComboBox();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 473, -1, -1));

        SenhaCadastro2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SenhaCadastro2KeyPressed(evt);
            }
        });
        getContentPane().add(SenhaCadastro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 420, 30));

        SenhaCadastro1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SenhaCadastro1KeyPressed(evt);
            }
        });
        getContentPane().add(SenhaCadastro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 420, 30));

        EmailCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmailCadastroKeyPressed(evt);
            }
        });
        getContentPane().add(EmailCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 420, 30));

        NomeCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomeCadastroKeyPressed(evt);
            }
        });
        getContentPane().add(NomeCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 420, 30));

        RSeguranca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RSegurancaKeyPressed(evt);
            }
        });
        getContentPane().add(RSeguranca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 423, 420, 32));

        PSegurancaCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha um item...", "Qual o nome da sua mãe?", "Qual o nome do seu ultimo animal de estimação?", "Qual o nome da sua primeira escola?", "Qual o nome do seu pai?", "Qual o seu livro favorito?", "Qual o seu filme favorito?", "Qual o nome da sua primeira professora?" }));
        PSegurancaCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PSegurancaComboKeyPressed(evt);
            }
        });
        getContentPane().add(PSegurancaCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 420, 33));

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Cadastro.png"))); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String VSenhaCadastro1=null,VSenhaCadastro2=null;
        VSenhaCadastro1=(String.valueOf(SenhaCadastro1.getPassword()));
        VSenhaCadastro2=(String.valueOf(SenhaCadastro2.getPassword()));
        
        if(NomeCadastro.getText().equals("")||EmailCadastro.getText().equals("")||VSenhaCadastro1.equals("")||VSenhaCadastro2.equals("")||PSegurancaCombo.getSelectedIndex()==0||RSeguranca.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
        }else{
            String SenhaCadastro = null;
            Usuario usuario = new Usuario(NomeCadastro.getText());

            if(String.valueOf(SenhaCadastro1.getPassword()).equals(String.valueOf(SenhaCadastro2.getPassword()))){
            SenhaCadastro=(String.valueOf(SenhaCadastro1.getPassword()));         
            usuario.setSenha(String.valueOf(SenhaCadastro));
            usuario.setEmail(String.valueOf(EmailCadastro.getText()));
            usuario.setPSeguranca(String.valueOf(PSegurancaCombo.getSelectedItem().toString()));
            usuario.setRSeguranca(String.valueOf(RSeguranca.getText()));
            
                if(usuario.validar(EmailCadastro.getText())){
                        if(Usuario.Cadastrar(usuario)){
                            JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
                            dispose();
                        }else{
                            JOptionPane.showMessageDialog(null, "Esse nome de usuario ja existe", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
                        }
                }else{
                    JOptionPane.showMessageDialog(null, "O e-mail digitado é invalido", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
                }        
            }else{
                JOptionPane.showMessageDialog(null, "Senhas diferentes", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
            }
           
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        

    }//GEN-LAST:event_formWindowClosed

    private void NomeCadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomeCadastroKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) { 
        String VSenhaCadastro1=null,VSenhaCadastro2=null;
        VSenhaCadastro1=(String.valueOf(SenhaCadastro1.getPassword()));
        VSenhaCadastro2=(String.valueOf(SenhaCadastro2.getPassword()));
        
        if(NomeCadastro.getText().equals("")||EmailCadastro.getText().equals("")||VSenhaCadastro1.equals("")||VSenhaCadastro2.equals("")||PSegurancaCombo.getSelectedIndex()==0||RSeguranca.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
        }else{
            String SenhaCadastro = null;
            Usuario usuario = new Usuario(NomeCadastro.getText());

            if(String.valueOf(SenhaCadastro1.getPassword()).equals(String.valueOf(SenhaCadastro2.getPassword()))){
            SenhaCadastro=(String.valueOf(SenhaCadastro1.getPassword()));         
            usuario.setSenha(String.valueOf(SenhaCadastro));
            usuario.setEmail(String.valueOf(EmailCadastro.getText()));
            usuario.setPSeguranca(String.valueOf(PSegurancaCombo.getSelectedItem().toString()));
            usuario.setRSeguranca(String.valueOf(RSeguranca.getText()));
            
                if(usuario.validar(EmailCadastro.getText())){
                        if(Usuario.Cadastrar(usuario)){
                            JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
                            dispose();
                        }else{
                            JOptionPane.showMessageDialog(null, "Esse nome de usuario ja existe", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
                        }
                }else{
                    JOptionPane.showMessageDialog(null, "O e-mail digitado é invalido", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
                }        
            }else{
                JOptionPane.showMessageDialog(null, "Senhas diferentes", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
            }
           
        }
        }
    }//GEN-LAST:event_NomeCadastroKeyPressed

    private void EmailCadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailCadastroKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) { 
        String VSenhaCadastro1=null,VSenhaCadastro2=null;
        VSenhaCadastro1=(String.valueOf(SenhaCadastro1.getPassword()));
        VSenhaCadastro2=(String.valueOf(SenhaCadastro2.getPassword()));
        
        if(NomeCadastro.getText().equals("")||EmailCadastro.getText().equals("")||VSenhaCadastro1.equals("")||VSenhaCadastro2.equals("")||PSegurancaCombo.getSelectedIndex()==0||RSeguranca.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
        }else{
            String SenhaCadastro = null;
            Usuario usuario = new Usuario(NomeCadastro.getText());

            if(String.valueOf(SenhaCadastro1.getPassword()).equals(String.valueOf(SenhaCadastro2.getPassword()))){
            SenhaCadastro=(String.valueOf(SenhaCadastro1.getPassword()));         
            usuario.setSenha(String.valueOf(SenhaCadastro));
            usuario.setEmail(String.valueOf(EmailCadastro.getText()));
            usuario.setPSeguranca(String.valueOf(PSegurancaCombo.getSelectedItem().toString()));
            usuario.setRSeguranca(String.valueOf(RSeguranca.getText()));
            
                if(usuario.validar(EmailCadastro.getText())){
                        if(Usuario.Cadastrar(usuario)){
                            JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
                            dispose();
                        }else{
                            JOptionPane.showMessageDialog(null, "Esse nome de usuario ja existe", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
                        }
                }else{
                    JOptionPane.showMessageDialog(null, "O e-mail digitado é invalido", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
                }        
            }else{
                JOptionPane.showMessageDialog(null, "Senhas diferentes", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
            }
           
        }
        }
    }//GEN-LAST:event_EmailCadastroKeyPressed

    private void SenhaCadastro1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SenhaCadastro1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) { 
        String VSenhaCadastro1=null,VSenhaCadastro2=null;
        VSenhaCadastro1=(String.valueOf(SenhaCadastro1.getPassword()));
        VSenhaCadastro2=(String.valueOf(SenhaCadastro2.getPassword()));
        
        if(NomeCadastro.getText().equals("")||EmailCadastro.getText().equals("")||VSenhaCadastro1.equals("")||VSenhaCadastro2.equals("")||PSegurancaCombo.getSelectedIndex()==0||RSeguranca.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
        }else{
            String SenhaCadastro = null;
            Usuario usuario = new Usuario(NomeCadastro.getText());

            if(String.valueOf(SenhaCadastro1.getPassword()).equals(String.valueOf(SenhaCadastro2.getPassword()))){
            SenhaCadastro=(String.valueOf(SenhaCadastro1.getPassword()));         
            usuario.setSenha(String.valueOf(SenhaCadastro));
            usuario.setEmail(String.valueOf(EmailCadastro.getText()));
            usuario.setPSeguranca(String.valueOf(PSegurancaCombo.getSelectedItem().toString()));
            usuario.setRSeguranca(String.valueOf(RSeguranca.getText()));
            
                if(usuario.validar(EmailCadastro.getText())){
                        if(Usuario.Cadastrar(usuario)){
                            JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
                            dispose();
                        }else{
                            JOptionPane.showMessageDialog(null, "Esse nome de usuario ja existe", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
                        }
                }else{
                    JOptionPane.showMessageDialog(null, "O e-mail digitado é invalido", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
                }        
            }else{
                JOptionPane.showMessageDialog(null, "Senhas diferentes", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
            }
           
        }
        }
    }//GEN-LAST:event_SenhaCadastro1KeyPressed

    private void SenhaCadastro2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SenhaCadastro2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) { 
        String VSenhaCadastro1=null,VSenhaCadastro2=null;
        VSenhaCadastro1=(String.valueOf(SenhaCadastro1.getPassword()));
        VSenhaCadastro2=(String.valueOf(SenhaCadastro2.getPassword()));
        
        if(NomeCadastro.getText().equals("")||EmailCadastro.getText().equals("")||VSenhaCadastro1.equals("")||VSenhaCadastro2.equals("")||PSegurancaCombo.getSelectedIndex()==0||RSeguranca.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
        }else{
            String SenhaCadastro = null;
            Usuario usuario = new Usuario(NomeCadastro.getText());

            if(String.valueOf(SenhaCadastro1.getPassword()).equals(String.valueOf(SenhaCadastro2.getPassword()))){
            SenhaCadastro=(String.valueOf(SenhaCadastro1.getPassword()));         
            usuario.setSenha(String.valueOf(SenhaCadastro));
            usuario.setEmail(String.valueOf(EmailCadastro.getText()));
            usuario.setPSeguranca(String.valueOf(PSegurancaCombo.getSelectedItem().toString()));
            usuario.setRSeguranca(String.valueOf(RSeguranca.getText()));
            
                if(usuario.validar(EmailCadastro.getText())){
                        if(Usuario.Cadastrar(usuario)){
                            JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
                            dispose();
                        }else{
                            JOptionPane.showMessageDialog(null, "Esse nome de usuario ja existe", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
                        }
                }else{
                    JOptionPane.showMessageDialog(null, "O e-mail digitado é invalido", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
                }        
            }else{
                JOptionPane.showMessageDialog(null, "Senhas diferentes", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
            }
           
        }
        }
    }//GEN-LAST:event_SenhaCadastro2KeyPressed

    private void RSegurancaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RSegurancaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) { 
        String VSenhaCadastro1=null,VSenhaCadastro2=null;
        VSenhaCadastro1=(String.valueOf(SenhaCadastro1.getPassword()));
        VSenhaCadastro2=(String.valueOf(SenhaCadastro2.getPassword()));
        
        if(NomeCadastro.getText().equals("")||EmailCadastro.getText().equals("")||VSenhaCadastro1.equals("")||VSenhaCadastro2.equals("")||PSegurancaCombo.getSelectedIndex()==0||RSeguranca.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
        }else{
            String SenhaCadastro = null;
            Usuario usuario = new Usuario(NomeCadastro.getText());

            if(String.valueOf(SenhaCadastro1.getPassword()).equals(String.valueOf(SenhaCadastro2.getPassword()))){
            SenhaCadastro=(String.valueOf(SenhaCadastro1.getPassword()));         
            usuario.setSenha(String.valueOf(SenhaCadastro));
            usuario.setEmail(String.valueOf(EmailCadastro.getText()));
            usuario.setPSeguranca(String.valueOf(PSegurancaCombo.getSelectedItem().toString()));
            usuario.setRSeguranca(String.valueOf(RSeguranca.getText()));
            
                if(usuario.validar(EmailCadastro.getText())){
                        if(Usuario.Cadastrar(usuario)){
                            JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
                            dispose();
                        }else{
                            JOptionPane.showMessageDialog(null, "Esse nome de usuario ja existe", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
                        }
                }else{
                    JOptionPane.showMessageDialog(null, "O e-mail digitado é invalido", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
                }        
            }else{
                JOptionPane.showMessageDialog(null, "Senhas diferentes", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
            }
           
        }
        }
    }//GEN-LAST:event_RSegurancaKeyPressed

    private void PSegurancaComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PSegurancaComboKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PSegurancaComboKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailCadastro;
    private javax.swing.JLabel Fundo;
    private javax.swing.JTextField NomeCadastro;
    private javax.swing.JComboBox PSegurancaCombo;
    private javax.swing.JTextField RSeguranca;
    private javax.swing.JPasswordField SenhaCadastro1;
    private javax.swing.JPasswordField SenhaCadastro2;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
