/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author CLP
 */
public class RecupSenha3 extends javax.swing.JFrame {
 
    Usuario usuario = new Usuario();
    
    /**
     * Creates new form RecupSenha3
     */
    public RecupSenha3(Usuario usuario) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.usuario=usuario;
    }

    private RecupSenha3() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(CSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 216, 33));

        jButton1.setText("Redefinir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 90, 100, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/RecSenha3.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String senha=(String.valueOf(CSenha.getPassword()));
        if(senha.equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo", "Erro", JOptionPane.WARNING_MESSAGE);
        }else{
            usuario.setSenha(senha);
            Usuario.RedefinirSenha(usuario);
            
            JOptionPane.showMessageDialog(null, "Senha alterada com sucesso", "Alterar Senha", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CSenhaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            String senha=(String.valueOf(CSenha.getPassword()));
            if(senha.equals("")){
                JOptionPane.showMessageDialog(null, "Preencha o campo", "Erro", JOptionPane.WARNING_MESSAGE);
            }else{
                usuario.setSenha(senha);
                Usuario.RedefinirSenha(usuario);
            
                JOptionPane.showMessageDialog(null, "Senha alterada com sucesso", "Alterar Senha", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
        }
    }//GEN-LAST:event_CSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecupSenha3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecupSenha3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecupSenha3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecupSenha3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecupSenha3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CSenha;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
