/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class RecupSenha extends javax.swing.JFrame {

    /**
     * Creates new form RecupSenha
     */
    public RecupSenha() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeU = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NomeU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomeUKeyPressed(evt);
            }
        });
        getContentPane().add(NomeU, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 213, 29));

        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 101, 90, -1));

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/RecSenha1.png"))); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(NomeU.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo", "Erro", JOptionPane.WARNING_MESSAGE);
        }else{
            if(Usuario.VerificarUsuarioRec(NomeU.getText())){
                Usuario usuario = new Usuario(NomeU.getText());
                RecupSenha2 recupsenha2 = new RecupSenha2(usuario);
                recupsenha2.setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Este usuário não existe", "Erro", JOptionPane.WARNING_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NomeUKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomeUKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            if(NomeU.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Preencha o campo", "Erro", JOptionPane.WARNING_MESSAGE);
            }else{
            if(Usuario.VerificarUsuarioRec(NomeU.getText())){
                Usuario usuario = new Usuario(NomeU.getText());
                RecupSenha2 recupsenha2 = new RecupSenha2(usuario);
                recupsenha2.setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Este usuário não existe", "Erro", JOptionPane.WARNING_MESSAGE);
            }
        }
        }
    }//GEN-LAST:event_NomeUKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecupSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecupSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecupSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecupSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecupSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JTextField NomeU;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
