/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bomberproject;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;

/**
 *
 * @author Aluno
 */
public class TelaJogo extends javax.swing.JFrame {

    /**
     * Creates new form TelaJogo
     */
    public TelaJogo() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("tank/TANKRED/down 1.png")));
        reseta();
        
    }

    static char sight='D';
    static char sight2='U';
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empate = new javax.swing.JLabel();
        explosion2 = new javax.swing.JLabel();
        explosion1 = new javax.swing.JLabel();
        shot = new javax.swing.JLabel();
        shot2 = new javax.swing.JLabel();
        TP1 = new javax.swing.JLabel();
        TP2 = new javax.swing.JLabel();
        gameOver = new javax.swing.JLabel();
        vidaEscuro2 = new javax.swing.JLabel();
        vidaEscuro1 = new javax.swing.JLabel();
        icnP1 = new javax.swing.JLabel();
        icnP2 = new javax.swing.JLabel();
        vida2 = new javax.swing.JLabel();
        vida1 = new javax.swing.JLabel();
        player1 = new javax.swing.JLabel();
        player2 = new javax.swing.JLabel();
        stageBackground = new javax.swing.JLabel();
        vidro = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();
        combustivel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RetroWar");
        setMinimumSize(new java.awt.Dimension(544, 574));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        empate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomberproject/ICN/Empate.png"))); // NOI18N
        getContentPane().add(empate, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 360, -1, -1));

        explosion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomberproject/BOOM/image_part_081.png"))); // NOI18N
        getContentPane().add(explosion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 100, 100));

        explosion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomberproject/BOOM/image_part_081.png"))); // NOI18N
        getContentPane().add(explosion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 100, 100));

        shot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomberproject/Bullet/baixored.png"))); // NOI18N
        getContentPane().add(shot, new org.netbeans.lib.awtextra.AbsoluteConstraints(-64, -64, 50, 50));

        shot2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomberproject/Bullet/baixoblue.png"))); // NOI18N
        getContentPane().add(shot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-64, -64, 50, 50));

        TP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomberproject/tank/TANKRED/down 1.png"))); // NOI18N
        getContentPane().add(TP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 32, 38, 64));

        TP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomberproject/tank/TANKBLUE/up 1.png"))); // NOI18N
        getContentPane().add(TP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 448, -1, -1));

        gameOver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomberproject/ICN/gameover.png"))); // NOI18N
        gameOver.setToolTipText("");
        getContentPane().add(gameOver, new org.netbeans.lib.awtextra.AbsoluteConstraints(-544, 0, -1, -1));

        vidaEscuro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomberproject/Lives/dark lines.png"))); // NOI18N
        getContentPane().add(vidaEscuro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 510, 0, 30));

        vidaEscuro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomberproject/Lives/dark lines.png"))); // NOI18N
        getContentPane().add(vidaEscuro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 0, 0, 30));

        icnP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomberproject/tank/TANKRED/down 1.png"))); // NOI18N
        getContentPane().add(icnP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 30));

        icnP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomberproject/tank/TANKBLUE/down 1.png"))); // NOI18N
        getContentPane().add(icnP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, -1, 32));

        vida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomberproject/Lives/lines.png"))); // NOI18N
        vida2.setToolTipText("");
        getContentPane().add(vida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 510, 510, 32));

        vida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomberproject/Lives/lines.png"))); // NOI18N
        getContentPane().add(vida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 0, 510, 30));

        player1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomberproject/ICN/Shadow.png"))); // NOI18N
        getContentPane().add(player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 64, -1, -1));

        player2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomberproject/ICN/Shadow.png"))); // NOI18N
        getContentPane().add(player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 448, -1, -1));

        stageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomberproject/ICN/background perfect.png"))); // NOI18N
        getContentPane().add(stageBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        vidro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomberproject/ICN/glass.png"))); // NOI18N
        getContentPane().add(vidro, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 32, 480, 480));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomberproject/ICN/oie_9163210zwHqIyv.gif"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        combustivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomberproject/ICN/Fuel 32.png"))); // NOI18N
        getContentPane().add(combustivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    if(BomberProject.gameover.para && evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_P){
            BomberProject.explode1.gameover=false;
            BomberProject.explode2.gameover=false;
            
            BomberProject.move.compx=64;BomberProject.move.compy=64;
            BomberProject.move.xl=64;BomberProject.move.yl=64;
            BomberProject.move2.compx=448;BomberProject.move2.compy=448;
            BomberProject.move2.xl=448;BomberProject.move2.yl=448;
            gameOver.setLocation(0, -544);
            
            //salva aqui
            int pontos=BomberProject.explode1.pontosp2+BomberProject.explode2.pontosp1;
            inserir(BomberProject.getNome(),pontos);
            //System.out.println("Pontos: "+pontos);
            //System.out.println("Nome: "+BomberProject.getNome());
            
            
            
            
            sight='D';
            sight2='U';
            TP1.setIcon(new ImageIcon(getClass().getResource("tank/TANKRED/down 1.png")));
            TP2.setIcon(new ImageIcon(getClass().getResource("tank/TANKBLUE/up 1.png")));
            
            BomberProject.explode1.vidap1=0;
            vidaEscuro1.setSize(0, 32);
            BomberProject.explode2.vidap2=0;
            vidaEscuro2.setSize(0, 32);
            
        player1.setLocation(BomberProject.move.compx, BomberProject.move.compy);
        player2.setLocation(BomberProject.move2.compx, BomberProject.move2.compy);
        BomberProject.tela.empate.setLocation(-190,448);
            BomberProject.gameover.para=false;
        
        }
        
        if(BomberProject.gameover.para==false){    
        if(evt.getKeyCode() == KeyEvent.VK_A){
            BomberProject.move.left=true;
            sight='L';
        }
        else if(evt.getKeyCode() == KeyEvent.VK_D){
            BomberProject.move.right=true;
            sight='R';
        }
        if(evt.getKeyCode() == KeyEvent.VK_W){
            BomberProject.move.up=true;
            sight='U';
        }
        else if(evt.getKeyCode() == KeyEvent.VK_S){
            BomberProject.move.down=true;
            sight='D';
        }
        
        
        if(evt.getKeyCode() == KeyEvent.VK_LEFT){
            BomberProject.move2.left=true;
            sight2='L';
        }
        else if(evt.getKeyCode() == KeyEvent.VK_RIGHT){
            BomberProject.move2.right=true;
            sight2='R';
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            BomberProject.move2.up=true;
            sight2='U';
        }
        else if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            BomberProject.move2.down=true;
            sight2='D';
        }
        
        
        if(evt.getKeyCode() == KeyEvent.VK_G || evt.getKeyCode() == KeyEvent.VK_SPACE){
            Shoot.imshooting=true;
        }
        if(evt.getKeyCode() == KeyEvent.VK_M || evt.getKeyCode() == KeyEvent.VK_NUMPAD0){
            Shoot2.imshooting=true;
        }
        
        
    }
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_A){
            BomberProject.move.left=false;
        }
        if(evt.getKeyCode() == KeyEvent.VK_D){
            BomberProject.move.right=false;
        }
        if(evt.getKeyCode() == KeyEvent.VK_W){
            BomberProject.move.up=false;
        }
        if(evt.getKeyCode() == KeyEvent.VK_S){
            BomberProject.move.down=false;
        }
        
        
        if(evt.getKeyCode() == KeyEvent.VK_LEFT){
            BomberProject.move2.left=false;
        }
        else if(evt.getKeyCode() == KeyEvent.VK_RIGHT){
            BomberProject.move2.right=false;
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            BomberProject.move2.up=false;
        }
        else if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            BomberProject.move2.down=false;
        }
    }//GEN-LAST:event_formKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        BomberProject.musica.clip.stop();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }
        });
    }

    
    
    public static void inserir(String Nome, int pontos) {
       // System.out.println("Valor final de pontos: "+ pontos);
       // System.out.println("nome final é: "+ Nome);
        
        
        boolean n=false;
        
        try {
            Connection conexao = Conexao.getConexao();
            Statement st = conexao.createStatement();
            
            String sql = "SELECT * FROM pontuacao where Usuario_Nome='"+Nome+"' and jogo_id=2";
            
            
            ResultSet rs = st.executeQuery(sql);
            
            n=rs.isBeforeFirst();
            
            if (!n){
                
                try {

                    //System.out.println("inseriu novo");
                    String sql2 = "INSERT INTO pontuacao VALUES ('"+ Nome +"',2,"+ pontos +")";

                    st.executeUpdate(sql2);

                }
                catch (Exception e) {
                    e.printStackTrace();
                }

            }else{
                try {

                    //System.out.println("Fez update");
                    String sql3 = "UPDATE pontuacao SET pontos = pontos + '"+ pontos +"' WHERE Usuario_Nome='"+Nome+"' and jogo_id=2";
                    
                    st.executeUpdate(sql3);

                }
                catch (Exception e) {
                    e.printStackTrace();
                }
            }   
            rs.close();
            st.close();
            Conexao.closeAll(conexao);
        }
        catch (Exception e) {
            e.printStackTrace();
            
        }
        

    }
    
    public static void reseta(){
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel TP1;
    public static javax.swing.JLabel TP2;
    public static javax.swing.JLabel combustivel;
    public static javax.swing.JLabel empate;
    public static javax.swing.JLabel explosion1;
    public static javax.swing.JLabel explosion2;
    private javax.swing.JLabel fundo;
    public static javax.swing.JLabel gameOver;
    private javax.swing.JLabel icnP1;
    private javax.swing.JLabel icnP2;
    public static javax.swing.JLabel player1;
    public static javax.swing.JLabel player2;
    public static javax.swing.JLabel shot;
    public static javax.swing.JLabel shot2;
    private javax.swing.JLabel stageBackground;
    private javax.swing.JLabel vida1;
    private javax.swing.JLabel vida2;
    public static javax.swing.JLabel vidaEscuro1;
    public static javax.swing.JLabel vidaEscuro2;
    private javax.swing.JLabel vidro;
    // End of variables declaration//GEN-END:variables
}
